package de.rwth_aachen.phyphox.common.camera.domain.model

import com.google.gson.annotations.SerializedName

typealias CameraInfoList = List<CameraInfo>
data class CameraInfo(
    @SerializedName("id")
    val id: String,

    @SerializedName("facing")
    val lensFacing: LensFacing,

    @SerializedName("hardwareLevel")
    val hardwareLevel: HardwareLevel,

    @SerializedName("capabilities")
    val capabilities: List<Capability>,

    @SerializedName("captureRequestKeys")
    val captureRequestKeys: List<String>,

    @SerializedName("captureResultKeys")
    val captureResultKeys: List<String>,

    @SerializedName("fpsRanges")
    val fpsRanges: List<FpsRange>,

    @SerializedName("physicalCamIds")
    val physicalCamIds: List<String>,

    @SerializedName("streamConfigurations")
    val streamConfigurations: List<StreamConfiguration>
)

enum class Capability{
    @SerializedName("CAPABILITIES_BACKWARD_COMPATIBLE") REQUEST_AVAILABLE_CAPABILITIES_BACKWARD_COMPATIBLE,
    @SerializedName("CAPABILITIES_MANUAL_SENSOR") REQUEST_AVAILABLE_CAPABILITIES_MANUAL_SENSOR,
    @SerializedName("CAPABILITIES_MANUAL_POST_PROCESSING") REQUEST_AVAILABLE_CAPABILITIES_MANUAL_POST_PROCESSING,
    @SerializedName("CAPABILITIES_RAW") REQUEST_AVAILABLE_CAPABILITIES_RAW,
    @SerializedName("CAPABILITIES_PRIVATE_REPROCESSING") REQUEST_AVAILABLE_CAPABILITIES_PRIVATE_REPROCESSING,
    @SerializedName("CAPABILITIES_READ_SENSOR_SETTINGS") REQUEST_AVAILABLE_CAPABILITIES_READ_SENSOR_SETTINGS,
    @SerializedName("CAPABILITIES_BURST_CAPTURE") REQUEST_AVAILABLE_CAPABILITIES_BURST_CAPTURE,
    @SerializedName("CAPABILITIES_YUV_REPROCESSING") REQUEST_AVAILABLE_CAPABILITIES_YUV_REPROCESSING,
    @SerializedName("CAPABILITIES_DEPTH_OUTPUT") REQUEST_AVAILABLE_CAPABILITIES_DEPTH_OUTPUT,
    @SerializedName("CAPABILITIES_CONSTRAINED_HIGH_SPEED_VIDEO") REQUEST_AVAILABLE_CAPABILITIES_CONSTRAINED_HIGH_SPEED_VIDEO,
    @SerializedName("CAPABILITIES_MOTION_TRACKING") REQUEST_AVAILABLE_CAPABILITIES_MOTION_TRACKING,
    @SerializedName("CAPABILITIES_LOGICAL_MULTI_CAMERA") REQUEST_AVAILABLE_CAPABILITIES_LOGICAL_MULTI_CAMERA,
    @SerializedName("CAPABILITIES_MONOCHROME") REQUEST_AVAILABLE_CAPABILITIES_MONOCHROME,
    @SerializedName("CAPABILITIES_SECURE_IMAGE_DATA") REQUEST_AVAILABLE_CAPABILITIES_SECURE_IMAGE_DATA,
    @SerializedName("CAPABILITIES_SYSTEM_CAMERA") REQUEST_AVAILABLE_CAPABILITIES_SYSTEM_CAMERA,
    @SerializedName("CAPABILITIES_OFFLINE_PROCESSING") REQUEST_AVAILABLE_CAPABILITIES_OFFLINE_PROCESSING,
    @SerializedName("CAPABILITIES_ULTRA_HIGH_RESOLUTION_SENSOR") REQUEST_AVAILABLE_CAPABILITIES_ULTRA_HIGH_RESOLUTION_SENSOR,
    @SerializedName("CAPABILITIES_REMOSAIC_REPROCESSING") REQUEST_AVAILABLE_CAPABILITIES_REMOSAIC_REPROCESSING,
    @SerializedName("CAPABILITIES_DYNAMIC_RANGE_TEN_BIT") REQUEST_AVAILABLE_CAPABILITIES_DYNAMIC_RANGE_TEN_BIT,
    @SerializedName("CAPABILITIES_STREAM_USE_CASE") REQUEST_AVAILABLE_CAPABILITIES_STREAM_USE_CASE,
    @SerializedName("CAPABILITIES_COLOR_SPACE_PROFILE") REQUEST_AVAILABLE_CAPABILITIES_COLOR_SPACE_PROFILES,
    @SerializedName("UNKNOWN") REQUEST_AVAILABLE_CAPABILITIES_UNKNOWN
}
